services:
  postgres:
    image: postgres:${POSTGRES_TAG}
    ports:
      - 5432:5432
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - kube_news_vol:/var/lib/postgresql/data
    networks:
      - kube_news_net
  kube_news:
    image: danieldeandrade/kube-news:${KUBENEWS_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: kube_news_app
    environment:
      DB_DATABASE: ${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${POSTGRES_CONTAINER_NAME}
    networks:
      - kube_news_net
    depends_on:
      - postgres

volumes:
  kube_news_vol:
    name: kube_news_vol

networks:
  kube_news_net:
    name: kube_news_net
    driver: bridge